
-- env setup 
--Drop table Workers; 

CREATE TABLE Workers (
	WORKER_ID INT NOT NULL PRIMARY KEY ,
	FIRST_NAME VARCHAR(25),
	LAST_NAME VARCHAR(25),
	SALARY INT,
	JOINING_DATE DATE,
	DEPARTMENT VARCHAR(25)
);

INSERT INTO Workers 
	(WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES
		(001, 'Jay', 'Arora', 100000, '2015-06-24', 'HR'),
		(002, 'Vijay', 'Verma', 80000, '2011-06-14', 'Admin'),
		(003, 'Sunil', 'Singhal', 300000, '2020-02-14', 'HR'),
		(004, 'Mahendra', 'Singh', 500000, '2020-02-14', 'Admin'),
		(005, 'Rashmi', 'Bhati', 500000, '2011-06-14', 'Admin'),
		(006, 'Anuskha', 'Diwan', 200000, '1011-06-14', 'Account'),
		(007, 'Manish', 'Kumar', 75000, '2020-01-14', 'Account'),
		(008, 'Rekha', 'Chauhan', 90000, '2011-04-14', 'Admin'),
(009, 'Sanjay', 'Sharma', null, '2015-06-23', 'HR'),
		(010, 'Anand', 'Joshi', null, '2012-06-15', 'Admin');

		--testing 
		select * from workers

		Solve 
--Select all records of Workers from table Workers 
--Ans : 
SELECT * FROM WORKERS

--1> FIND ALL THE DETAILS  OF WORKER WHO'S ID IS 4
select * from workers where worker_id = 4 

-- FIND ALL WORKERS WHO'S SALARIES ARE MORE THAN 100000
SELECT FIRST_NAME + ' ' + LAST_NAME EMPLOYEE FROM WORKERS WHERE SALARY > 100000

-- 3> FIND THE FIRST NAME AND SALARY DETAILS OF WORKERS FROM ACCOUNT DEPARTMENT 
SELECT FIRST_NAME,SALARY FROM WORKERS WHERE DEPARTMENT = 'Account'

--4> SEARCH FIRST NAME AND JOINING DATE OF WORKERS FROM HR DEPARTMENT 
SELECT FIRST_NAME,JOINING_DATE FROM WORKERS WHERE DEPARTMENT = 'HR'

--5> FIND ALL THE WORKERS WHO ARE EARNING MORE THAN 10000 SALARIES FROM HR DEPARTMENT 
 SELECT FIRST_NAME,JOINING_DATE FROM WORKERS WHERE DEPARTMENT = 'HR' AND SALARY > 10000

--6> SEARCH ALL THE WORKERS FROM DEPARTMENT ADMIN AND HR WITHOUT USE OF IN OPERATOR 
SELECT FIRST_NAME + ' ' + LAST_NAME EMPLOYEE FROM WORKERS WHERE DEPARTMENT = 'HR' OR DEPARTMENT = 'ADMIN'

--7> FIND THE DETAILS OF WORKERS WITH IDS 3, 6, 7
SELECT * FROM WORKERS WHERE WORKER_ID IN (3,6,7)

--8> FIND THE DETAILS OF WORKERS WITH IDS STARTING FROM 2 TO 7 
SELECT * FROM WORKERS WHERE WORKER_ID BETWEEN 2 AND 7

--9> FIND THE DETAILS OF WORKERS WHO'S SALARIES ARE WITHIN RANGE OF 100000 TO 30000
SELECT * FROM WORKERS WHERE SALARY < 100000 AND SALARY > 30000


--10> LIST ALL AVAILABLE DEPARTMENTS ( DON'T DISPLAY DUPLICATE RECORDS ) 
SELECT DISTINCT DEPARTMENT FROM WORKERS


--11> FIND ALL WORKERS WHO'S NAMES START WITH 'R' 
SELECT FIRST_NAME, LAST_NAME FROM WORKERS WHERE FIRST_NAME LIKE 'R%'

